# Site-wide settings
# ------------------

title: Struan Stevenson

author:
  name: Struan Stevenson
  email: struan.stevenson@ed.ac.uk

description: Institute for Astronomy, Royal Observatory Edinburgh, Blackford Hill, Edinburgh EH9 3HJ

theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: classic

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - about.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  social_links:
    - title: Github profile
      icon: github
      url: "https://github.com/strusteve"
    - title: Orcid profile
      icon: orcid
      url: "https://orcid.org/my-orcid?orcid=0000-0001-5642-752X"

  
#google_analytics: G-NNNNNNNNNN  
